version: "3.9"
services:
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: ${DB_SERVICENAME}
        deploy:
            labels: [APP=sqlserver]
        ports:
            - "${DB_EXTERNALPORT}:${DB_INTERNALPORT}"
        env_file: 
            - .env
        
    db-sidecar:
        image: dsoderlund/dbatools-restapi:latest
        container_name: sidecar
        deploy:
            labels: [APP=pode]
        ports:
            - "8080:8080"
        depends_on:
            - db
        links:
            - "db:${DB_SERVICENAME}"
        env_file: 
            - .env
    