name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PSGallery
        id: psgallerycheck
        shell: pwsh
        run: |
          try {
            $code = Invoke-WebRequest -Uri https://www.powershellgallery.com `
              -UseBasicParsing -ErrorAction SilentlyContinue `
              -ConnectionTimeoutSeconds 10 -OperationTimeoutSeconds 1 `
              | Select-Object -ExpandProperty StatusCode;
            if ($code -ge 400) { throw $code; }
          } catch {
            Write-Host -ForegroundColor Red "$_.Message";
            throw 'PowerShell Gallery is not available';
          }
      - name: Check Out Repo 
        id: checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
            image: ${{ secrets.DOCKER_HUB_USERNAME }}/dbatools-restapi
            tags:  latest, $(date +%s)
            registry: docker.io
            dockerfile: Dockerfile
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            