name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo 
        id: checkout
        uses: actions/checkout@v2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.3
        with:
          image: ${{ secrets.DOCKER_HUB_USERNAME }}/dbatools-restapi
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
            